apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiredis
  namespace: so1p2
  labels:
    role: apiredis
spec:
  replicas: 1
  selector:
    matchLabels:
      role: apiredis
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        role: apiredis
    spec:
      containers:
      - name: apiredis
        image: sergio10rpr/api-redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: apiredis
  namespace: so1p2
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
  selector:
    role: apiredis