apiVersion: apps/v1
kind: Deployment
metadata:
  name: apinode
  namespace: so1p2
  labels:
    role: apinode
spec:
  replicas: 2
  selector:
    matchLabels:
      role: apinode
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        role: apinode
    spec:
      containers:
      - name: apinode
        image: sergio10rpr/apinodejs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: apinode
  namespace: so1p2
spec:
  type: LoadBalancer
  ports:
  - port: 3004
    targetPort: 3003
  selector:
    role: apinode